/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cifrado.cifradofinal;

import java.io.DataOutputStream;
import java.net.Socket;

/**
 *
 * @author shyne
 */
public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMensaje = new javax.swing.JTextField();
        btnEncriptar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLlave = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEncriptado = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel1.setText("Texto a Encriptar:");

        btnEncriptar.setBackground(new java.awt.Color(255, 153, 102));
        btnEncriptar.setText("ENCRIPTAR");
        btnEncriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncriptarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setText("EMISOR");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel3.setText("Llave Generada:");
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 12));

        txtLlave.setBackground(new java.awt.Color(204, 204, 204));
        txtLlave.setColumns(20);
        txtLlave.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        txtLlave.setRows(5);
        txtLlave.setBorder(null);
        txtLlave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtLlave.setFocusable(false);
        jScrollPane1.setViewportView(txtLlave);

        txtEncriptado.setBackground(new java.awt.Color(204, 204, 204));
        txtEncriptado.setColumns(20);
        txtEncriptado.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        txtEncriptado.setRows(5);
        txtEncriptado.setBorder(null);
        txtEncriptado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtEncriptado.setFocusable(false);
        jScrollPane2.setViewportView(txtEncriptado);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel4.setText("Texto Generado:");
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 12));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtMensaje)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(btnEncriptar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEncriptar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3)
                        .addGap(57, 57, 57))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)
                        .addGap(57, 57, 57))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncriptarActionPerformed
        
        try{
            Socket socket = new Socket("10.100.100.92", 9999); //Primero va la ip, y segundo el puerto
            DataOutputStream envio = new DataOutputStream(socket.getOutputStream());
            
            String mensaje;
            char caracter;
            int codigoAscii;
            int intercambioValor1, intercambioValor2, intercambioValor3, intercambioValor4;
            String binario;

            String encriptado = "";
            String llave = "";
            mensaje = txtMensaje.getText();
            for (int i = 0; i < mensaje.length(); i++) {
                caracter = mensaje.charAt(i);
                //System.out.println("caracter mensajecharat: "+ caracter);
                codigoAscii = caracter;
                System.out.println(codigoAscii);
                binario = "";
                //System.out.println("caracter 1: "+ caracter + " numero: "+ codigoAscii);
                //letras son 8 digitos en ASCII

                for (int j = 7; j >= 0; j--) {
                    boolean codigo = codigoAscii >= Math.pow(2, j);
                    if (codigo) {
                        //para que no me repita el anterior
                        codigoAscii -= Math.pow(2, j);

                        binario = binario.concat("1");
                    } else {
                        binario = binario.concat("0");
                    }
                    System.out.println(binario);
                }

                do {
                    intercambioValor1 = (int) (Math.random() * 10);
                    System.out.println("int 1: "+intercambioValor1);
                } while (intercambioValor1 > 7);
                do {
                    intercambioValor2 = (int) (Math.random() * 10);
                    System.out.println("int 2: "+intercambioValor2);
                } while (intercambioValor2 > 7 || intercambioValor2 == intercambioValor1);
                do {
                    intercambioValor3 = (int) (Math.random() * 10);
                    System.out.println("int 3: "+intercambioValor3);
                } while (intercambioValor3 > 7 || intercambioValor3 == intercambioValor1
                        || intercambioValor3 == intercambioValor2);
                do {
                    intercambioValor4 = (int) (Math.random() * 10);
                    System.out.println("int 4: "+intercambioValor3);
                } while (intercambioValor4 > 7 || intercambioValor4 == intercambioValor1
                        || intercambioValor4 == intercambioValor2 || intercambioValor4 == intercambioValor3);
                String binarioEncriptado = "";
                for (int x = 0; x < 8; x++) {
                    caracter = binario.charAt(x);
                    //mediante 4 digitos se intercambian los 4 valores
                    //es decir que el binario original se swapea valor por valor
                    //si
                    if (x == intercambioValor1) caracter = binario.charAt(intercambioValor2);
                    if (x == intercambioValor2) caracter = binario.charAt(intercambioValor1);
                    if (x == intercambioValor3) caracter = binario.charAt(intercambioValor4);
                    if (x == intercambioValor4) caracter = binario.charAt(intercambioValor3);
                    System.out.println("a: "+intercambioValor1+" "+" b: "+intercambioValor2+
                            " c: "+intercambioValor3+ " d: "+intercambioValor4);
                    System.out.print("caracter: "+caracter);
                    binarioEncriptado = binarioEncriptado.concat(Character.toString(caracter));

                }
                encriptado = encriptado.concat(binarioEncriptado);

                llave = llave.concat(String.valueOf(intercambioValor1) + String.valueOf(intercambioValor2
                        + String.valueOf(intercambioValor3 + String.valueOf(intercambioValor4))));


            }
                envio.writeUTF(encriptado);
                envio.writeUTF(llave);
                
                txtLlave.setText(llave);
                txtEncriptado.setText(encriptado);
                socket.close();
            }catch(Exception e){
                System.out.println(e);
            }

            //IP PC Fernando : 10.100.100.92
    }//GEN-LAST:event_btnEncriptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEncriptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtEncriptado;
    private javax.swing.JTextArea txtLlave;
    private javax.swing.JTextField txtMensaje;
    // End of variables declaration//GEN-END:variables
}
