package pojos;
// Generated 6 feb. 2023 9:34:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Libros generated by hbm2java
 */
public class Libros  implements java.io.Serializable {


     private Integer idlibros;
     private String titulo;
     private String autor;
     private Set prestamoses = new HashSet(0);

    public Libros() {
    }
    
    public Libros(int idLibro) {
      this.idlibros=idLibro;
    }
    
    public Libros(String titulo, String autor, Set prestamoses) {
       this.titulo = titulo;
       this.autor = autor;
       this.prestamoses = prestamoses;
    }
   
    public Integer getIdlibros() {
        return this.idlibros;
    }
    
    public void setIdlibros(Integer idlibros) {
        this.idlibros = idlibros;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public Set getPrestamoses() {
        return this.prestamoses;
    }
    
    public void setPrestamoses(Set prestamoses) {
        this.prestamoses = prestamoses;
    }




}


