package pojos;
// Generated 6 feb. 2023 9:34:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Prestamos generated by hbm2java
 */
public class Prestamos  implements java.io.Serializable {


     private Integer idprestamos;
     private Libros libros;
     private Usuario usuario;
     private Date fechaPrestamo;
     private Date fechaDevolucion;
     private Date fechaRealDev;

    public Prestamos() {
    }

    public Prestamos(Libros libros, Usuario usuario, Date fechaPrestamo, Date fechaDevolucion, Date fechaRealDev) {
       this.libros = libros;
       this.usuario = usuario;
       this.fechaPrestamo = fechaPrestamo;
       this.fechaDevolucion = fechaDevolucion;
       this.fechaRealDev = fechaRealDev;
    }
   
    public Integer getIdprestamos() {
        return this.idprestamos;
    }
    
    public void setIdprestamos(Integer idprestamos) {
        this.idprestamos = idprestamos;
    }
    public Libros getLibros() {
        return this.libros;
    }
    
    public void setLibros(Libros libros) {
        this.libros = libros;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaPrestamo() {
        return this.fechaPrestamo;
    }
    
    public void setFechaPrestamo(Date fechaPrestamo) {
        this.fechaPrestamo = fechaPrestamo;
    }
    public Date getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(Date fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }
    public Date getFechaRealDev() {
        return this.fechaRealDev;
    }
    
    public void setFechaRealDev(Date fechaRealDev) {
        this.fechaRealDev = fechaRealDev;
    }




}


