package pojos;
// Generated 17 feb. 2023 14:17:22 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


     private String idCarrera;
     private String circuito;
     private Integer categoria;
     private Integer record;
     private Date fecha;
     private Set corres = new HashSet(0);

    public Carrera() {
    }
    
    public Carrera(String id){
        this.idCarrera = id;
    }
	
    public Carrera(String idCarrera, String circuito) {
        this.idCarrera = idCarrera;
        this.circuito = circuito;
    }
    public Carrera(String idCarrera, String circuito, Integer categoria, Integer record, Date fecha, Set corres) {
       this.idCarrera = idCarrera;
       this.circuito = circuito;
       this.categoria = categoria;
       this.record = record;
       this.fecha = fecha;
       this.corres = corres;
    }
   
    public String getIdCarrera() {
        return this.idCarrera;
    }
    
    public void setIdCarrera(String idCarrera) {
        this.idCarrera = idCarrera;
    }
    public String getCircuito() {
        return this.circuito;
    }
    
    public void setCircuito(String circuito) {
        this.circuito = circuito;
    }
    public Integer getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Integer categoria) {
        this.categoria = categoria;
    }
    public Integer getRecord() {
        return this.record;
    }
    
    public void setRecord(Integer record) {
        this.record = record;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getCorres() {
        return this.corres;
    }
    
    public void setCorres(Set corres) {
        this.corres = corres;
    }




}


