package pojos;
// Generated 17 feb. 2023 14:17:22 by Hibernate Tools 4.3.1



/**
 * CorreId generated by hbm2java
 */
public class CorreId  implements java.io.Serializable {


     private int piloto;
     private String carrera;

    public CorreId() {
    }

    public CorreId(int piloto, String carrera) {
       this.piloto = piloto;
       this.carrera = carrera;
    }
   
    public int getPiloto() {
        return this.piloto;
    }
    
    public void setPiloto(int piloto) {
        this.piloto = piloto;
    }
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CorreId) ) return false;
		 CorreId castOther = ( CorreId ) other; 
         
		 return (this.getPiloto()==castOther.getPiloto())
 && ( (this.getCarrera()==castOther.getCarrera()) || ( this.getCarrera()!=null && castOther.getCarrera()!=null && this.getCarrera().equals(castOther.getCarrera()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPiloto();
         result = 37 * result + ( getCarrera() == null ? 0 : this.getCarrera().hashCode() );
         return result;
   }   


}


