package pojos;
// Generated 17 feb. 2023 14:17:22 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private int idEquipo;
     private String nombre;
     private Date fecCrea;
     private byte eliminado;
     private String patroc;
     private Integer htot;
     private Set pilotos = new HashSet(0);

    public Equipo() {
    }

	
    public Equipo(int idEquipo, String nombre, Date fecCrea, byte eliminado) {
        this.idEquipo = idEquipo;
        this.nombre = nombre;
        this.fecCrea = fecCrea;
        this.eliminado = eliminado;
    }
    public Equipo(int idEquipo, String nombre, Date fecCrea, byte eliminado, String patroc, Integer htot, Set pilotos) {
       this.idEquipo = idEquipo;
       this.nombre = nombre;
       this.fecCrea = fecCrea;
       this.eliminado = eliminado;
       this.patroc = patroc;
       this.htot = htot;
       this.pilotos = pilotos;
    }
   
    public int getIdEquipo() {
        return this.idEquipo;
    }
    
    public void setIdEquipo(int idEquipo) {
        this.idEquipo = idEquipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFecCrea() {
        return this.fecCrea;
    }
    
    public void setFecCrea(Date fecCrea) {
        this.fecCrea = fecCrea;
    }
    public byte getEliminado() {
        return this.eliminado;
    }
    
    public void setEliminado(byte eliminado) {
        this.eliminado = eliminado;
    }
    public String getPatroc() {
        return this.patroc;
    }
    
    public void setPatroc(String patroc) {
        this.patroc = patroc;
    }
    public Integer getHtot() {
        return this.htot;
    }
    
    public void setHtot(Integer htot) {
        this.htot = htot;
    }
    public Set getPilotos() {
        return this.pilotos;
    }
    
    public void setPilotos(Set pilotos) {
        this.pilotos = pilotos;
    }




}


