package pojos;
// Generated 17 feb. 2023 14:17:22 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Piloto generated by hbm2java
 */
public class Piloto  implements java.io.Serializable {


     private int idPiloto;
     private Equipo equipo;
     private String nombre;
     private Date FIncorp;
     private byte sancionado;
     private Set corres = new HashSet(0);

    public Piloto() {
    }
    
    public Piloto(int id){
        this.idPiloto = id;
    }
    
	
    public Piloto(int idPiloto, Equipo equipo, String nombre, Date FIncorp, byte sancionado) {
        this.idPiloto = idPiloto;
        this.equipo = equipo;
        this.nombre = nombre;
        this.FIncorp = FIncorp;
        this.sancionado = sancionado;
    }
    public Piloto(int idPiloto, Equipo equipo, String nombre, Date FIncorp, byte sancionado, Set corres) {
       this.idPiloto = idPiloto;
       this.equipo = equipo;
       this.nombre = nombre;
       this.FIncorp = FIncorp;
       this.sancionado = sancionado;
       this.corres = corres;
    }
   
    public int getIdPiloto() {
        return this.idPiloto;
    }
    
    public void setIdPiloto(int idPiloto) {
        this.idPiloto = idPiloto;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFIncorp() {
        return this.FIncorp;
    }
    
    public void setFIncorp(Date FIncorp) {
        this.FIncorp = FIncorp;
    }
    public byte getSancionado() {
        return this.sancionado;
    }
    
    public void setSancionado(byte sancionado) {
        this.sancionado = sancionado;
    }
    public Set getCorres() {
        return this.corres;
    }
    
    public void setCorres(Set corres) {
        this.corres = corres;
    }




}


